---

- name: Post Config Master
  hosts: masters[0]
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - ldap_groupsync

- name: Post Config All Hosts
  hosts: nodes
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - enable_yum_plugins
    - node-config
