---

- name: Copy add.txt to nodes
  copy:
    src: playbooks/roles/node-config/files/add.txt
    dest: add.txt

- name: Run sed command to append into node-config.yml
  shell: sed -i '/kubeletArguments:/r add.txt' /etc/origin/node/node-config.yaml

- name: Restart atomic-openshift-node
  shell: systemctl restart atomic-openshift-node
