kind: LDAPSyncConfig
apiVersion: v1
url: ldaps://ldapserver.com
bindDN: CN=s-openshift,OU=Service Accounts,OU=AD Admins,OU=XXX,DC=XXX,DC=ORG
bindPassword: XXXXX
insecure: false
groupUIDNameMapping:
    "CN=ocpAdmin,OU=XXX,OU=XXX,DC=XXX,DC=ORG": ocpAdmin
    "CN=ocpDeveloper,OU=XXX,OU=XXX,DC=XXX,DC=ORG": ocpDeveloper
activeDirectory:
    usersQuery:
        baseDN: "DC=XXX,DC=ORG"
        scope: sub
        derefAliases: never
        filter: (objectClass=person)
        pageSize: 0
    userNameAttributes: [ displayName ]
    groupMembershipAttributes: [ "memberof:1.2.840.113556.1.4.1941:" ]
    tolerateMemberOfNotFoundErrors: true
    tolerateMemberOutOfScopeErrors: true
