---
- name: Copy ldap_groupsync.yml to masters[0]
  hosts: masters[0]
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: /home/rhc/playbooks/roles/ldap_groupsync/files/ldap_groupsync.yml
    dest: /home/rhc/ldap_groupsync.yml

- name: Copy whitelist.txt to masters[0]
  hosts: masters[0]
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: /home/rhc/playbooks/roles/ldap_groupsync/files/whitelist.txt
    dest: /home/rhc/whitelist.txt 

- name: Setup cronjob for ldap_groupsync
  hosts: masters[0]
  become: yes
  become_user: root
  become_method: sudo
  cron:
    name: "ldap group sync"
    minute: "30"
    job: "oc adm groups sync --whitelist=/home/rhc/whitelist.txt --sync-config=/home/rhc/ldap_groupsync.yml --confirm"

- name: Run initial group sync
  hosts: masters[0]
  become: yes
  shell: oc adm groups sync --whitelist=/home/rhc/whitelist.txt --sync-config=/home/rhc/ldap_groupsync.yml --confirm
